### ISSUE TITLE
BootstrapVueの日付入力に関して、改善の余地あり

### ISSUE THREAD

**Issue by monomonosu** [gamasenninn/sohoweb#133]
BootstrapVueの<b-form-input type="date">は日付指定時には日にちまでの情報(%Y-%m-%d)が入るが、日付未指定時には秒数までの情報(%Y-%m-%d %H:%M:%S)が入ってしまう。
フロント側で日付指定のフォームを変更した方がいい？

**Comment by gamasenninn** [comment]
日付未指定時のときのDBデータを見せてみて

**Comment by monomonosu** [comment]
DB自分で見てみたのだが、なるほど。請求書と見積書のapplyDate（日にち）、expiry（有効期限）のデータ型をDateTileにしてしまっていたのが原因みたいだ。
さらにはseederでdatetime型を流している。
フロント側の入力はdate型なのでそりゃあバッティングするわけだ。
この辺の理解度、浅かったので勉強になった。

タスク
- [ ] 請求書のスキーマの変更。seederの変更。
- [ ] 見積書のスキーマの変更。seederの変更。
