### ISSUE TITLE
[請求書・見積書]itemsの項目を英語表記に変更

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/sohoweb#49]
請求書・見積書のコード内のitemsデータ、suryo,tanka,kingakuという日本語表記になっているが、頭悪そうなので英語表記に変更したよね。
これが参考になりそう。
[請求書の単語集](https://www.misoca.jp/study/invoice/bill-wordbook/)
suryo ---> quantity
tanka ----> unitPrice
kingaku ---> amount
goukei ----> total
全部の合計 ---->  sumTotal
ってどうだろう。

**Comment by monomonosu** [comment]
うん、その方が良さそうだね。
英語表記を基本にしよう

**Comment by gamasenninn** [comment]
モデル設計の時点で、ほぼすべて英語表記になっているので、このタスクは終了とします。
