### ISSUE TITLE
ORMは何にすべきか議論したい

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/sohoweb#59]
DBとのORMインターフェースは何にすべきか。

1. 独自で作る
2. SQLAlchemy
3. Django
4. Laravel
5. その他

ワシとしては2を推薦したい。
理由としては、次のとおり

- FaskのORMといったらこれが定番だから。
- 日本語ノウハウもある程度ある。
- 今回はインターフェースファースト的な開発だから、画面の仕様しだいでモデルがガンガン変わるので。
- DjangoやLaravelのようにフルスタックなフレームワークは必要ないと思われる。
- 独自でラッパー作るのもよいが、今回のアプリはスケールアップが予想されるので、モデルを固められるものがよい。

**Comment by monomonosu** [comment]
聞いたことないフレームワークだが、それで大丈夫だよ。
少しだけ調べたけど、使いやすそうだね

**Comment by gamasenninn** [comment]
じゃあさっそく実装の準備するね。

**Comment by gamasenninn** [comment]
SQL Alchemyの実験した。
API実装は地道な努力が必要そうだ。
Json変換すらマップが必要というのにはびっくり。
自分でつくったなんちゃってラッパーのほうが、実装は楽だとわかった。
でも、ORMなら複雑な構造もAPI内で実装できそうなので、そこいらへんは捨てがたい。
構造もModelで定義すれば、きっちりしたデータ構造が見える化するので、メンテは楽になるのは確実。
